In [1]:
import numpy as np

In [2]:
x = np.array(([0,0],[0,1],[1,0],[1,1]),dtype = float)
y = np.array(([0],[1],[1],[1]),dtype = float)
print(x)
print(y)

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
[[0.]
 [1.]
 [1.]
 [1.]]


In [3]:
class Neural_networks():
    def __init__(self):
        self.inputlayer = 2
        self.hiddenlayer = 3
        self.outputlayer = 1
        
        np.random.seed(0)

        self.w1 = np.random.randn(self.inputlayer,self.hiddenlayer)
        self.w2 = np.random.randn(self.hiddenlayer,self.outputlayer)
        print("w1:",self.w1)
        print("w2:",self.w2)
        
    def sigmoid(self,s):
        return 1/(1+np.exp(-s))
    
    def sigmoidprime(self,s):
        return s*(1-s)
        
    def forward(self,x):
        self.z = np.dot(x,self.w1)
        self.z2 = self.sigmoid(self.z)
        self.z3 = np.dot(self.z2,self.w2)
        
        O = self.sigmoid(self.z3)
        return O
    
    def backward(self,x,y,O):
        self.O_error = y-O
        self.O_delta = self.O_error*self.sigmoidprime(O)
        self.z2_error = self.O_delta.dot(self.w2.T)
        self.z2_delta = self.z2_error*self.sigmoidprime(self.z2)
        self.w1 += x.T.dot(self.z2_delta)
        self.w2 += self.z2.T.dot(self.O_delta)
        
    def train(self,x,y):
        O = self.forward(x)
        self.backward(x,y,O)
        

In [4]:
NN = Neural_networks()
for i in range(1000):
    print("INPUT:\n" + str(x))
    print("ACTUAL OP:\n" + str(y))
    print("PREDICTED OP:\n" + str(NN.forward(x)))
    print("LOSS:\n" + str(np.mean(np.square(y-NN.forward(x)))))
    print("\n")
    NN.train(x,y)

w1: [[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]]
w2: [[ 0.95008842]
 [-0.15135721]
 [-0.10321885]]
INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.58607335]
 [0.66805998]
 [0.6559865 ]
 [0.6779312 ]]
LOSS:
0.1689349397634204


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.61890693]
 [0.71475453]
 [0.70051174]
 [0.72844498]]
LOSS:
0.1569615290175024


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.6381632 ]
 [0.74199438]
 [0.7258848 ]
 [0.75711026]]
LOSS:
0.15198843442662202


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.65023556]
 [0.75944931]
 [0.7415931 ]
 [0.77499315]]
LOSS:
0.14951827957765546


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.65810578]
 [0.77140257]
 [0.75184808]
 [0.78690102]]
LO

PREDICTED OP:
[[0.2976153 ]
 [0.87294943]
 [0.84828057]
 [0.91967487]]
LOSS:
0.03354690617235782


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.2953964 ]
 [0.87347535]
 [0.84943444]
 [0.92013982]]
LOSS:
0.033078788754491585


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.29321266]
 [0.87400068]
 [0.85057039]
 [0.92059881]]
LOSS:
0.03262081243704382


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.29106343]
 [0.87452524]
 [0.85168872]
 [0.92105192]]
LOSS:
0.03217271715412601


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.28894803]
 [0.87504883]
 [0.85278972]
 [0.92149925]]
LOSS:
0.03173424892413038


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.28686582]
 [0.87557127]
 [0.85387367]
 [0.92194087]]
LOSS:
0.03130515984888374


INPUT

INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.14565229]
 [0.92606568]
 [0.92682002]
 [0.95528736]]
LOSS:
0.008508850364432097


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.14526898]
 [0.92623748]
 [0.92701539]
 [0.95538788]]
LOSS:
0.008465244696088727


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.14488835]
 [0.92640823]
 [0.92720938]
 [0.95548775]]
LOSS:
0.008422049132688958


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.14451038]
 [0.92657794]
 [0.927402  ]
 [0.95558699]]
LOSS:
0.008379258187236071


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.14413503]
 [0.92674661]
 [0.92759328]
 [0.9556856 ]]
LOSS:
0.00833686646673173


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.143

INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.10917379]
 [0.9430519 ]
 [0.9453634 ]
 [0.96514412]]
LOSS:
0.004840523130730106


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.10899856]
 [0.94313638]
 [0.94545227]
 [0.96519297]]
LOSS:
0.004825285507924971


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.10882412]
 [0.94322052]
 [0.94554075]
 [0.96524162]]
LOSS:
0.004810138217342297


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.10865044]
 [0.94330432]
 [0.94562883]
 [0.96529007]]
LOSS:
0.004795080483346186


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.10847752]
 [0.94338777]
 [0.94571652]
 [0.96533832]]
LOSS:
0.004780111538958036


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.10

INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.07210132]
 [0.96145787]
 [0.96413634]
 [0.97584926]]
LOSS:
0.002138389199679196


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.07204658]
 [0.96148577]
 [0.96416402]
 [0.97586566]]
LOSS:
0.0021351848321806786


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.07199196]
 [0.96151361]
 [0.96419164]
 [0.97588204]]
LOSS:
0.002131989713796168


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.07193746]
 [0.9615414 ]
 [0.9642192 ]
 [0.97589838]]
LOSS:
0.002128803805291385


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.07188307]
 [0.96156913]
 [0.96424671]
 [0.97591468]]
LOSS:
0.0021256270676508634


INPUT:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
ACTUAL OP:
[[0.]
 [1.]
 [1.]
 [1.]]
PREDICTED OP:
[[0.