In [1]:
import numpy as np

In [2]:
x = np.array(([2,9],[1,5],[3,6]),dtype = float)
y = np.array(([98],[89],[83]),dtype = float)
x = x/np.amax(x,axis=0)
y = y/100
print(x)
print(y)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.98]
 [0.89]
 [0.83]]


In [3]:
class Neural_networks():
    def __init__(self):
        self.inputlayer = 2
        self.hiddenlayer = 3
        self.outputlayer = 1
        
        np.random.seed(0)

        self.w1 = np.random.randn(self.inputlayer,self.hiddenlayer)
        self.w2 = np.random.randn(self.hiddenlayer,self.outputlayer)
        print("w1:",self.w1)
        print("w2:",self.w2)
        
    def sigmoid(self,s):
        return 1/(1+np.exp(-s))
    
    def sigmoidprime(self,s):
        return s*(1-s)
        
    def forward(self,x):
        self.z = np.dot(x,self.w1)
        self.z2 = self.sigmoid(self.z)
        self.z3 = np.dot(self.z2,self.w2)
        
        O = self.sigmoid(self.z3)
        return O
    
    def backward(self,x,y,O):
        self.O_error = y-O
        self.O_delta = self.O_error*self.sigmoidprime(O)
        self.z2_error = self.O_delta.dot(self.w2.T)
        self.z2_delta = self.z2_error*self.sigmoidprime(self.z2)
        self.w1 += x.T.dot(self.z2_delta)
        self.w2 += self.z2.T.dot(self.O_delta)
        
    def train(self,x,y):
        O = self.forward(x)
        self.backward(x,y,O)
        

In [4]:
NN = Neural_networks()
for i in range(2000):
    print("INPUT:\n" + str(x))
    print("ACTUAL OP:\n" + str(y))
    print("PREDICTED OP:\n" + str(NN.forward(x)))
    print("LOSS:\n" + str(np.mean(np.square(y-NN.forward(x)))))
    print("\n")
    NN.train(x,y)

w1: [[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]]
w2: [[ 0.95008842]
 [-0.15135721]
 [-0.10321885]]
INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.67727117]
 [0.65870127]
 [0.67437581]]
LOSS:
0.056454244642676316


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.73548268]
 [0.71286122]
 [0.73360537]]
LOSS:
0.03348626442750548


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.77062708]
 [0.74625585]
 [0.76932782]]
LOSS:
0.022726836816305166


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.79412241]
 [0.76895122]
 [0.79318278]]
LOSS:
0.01685293140337853


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55

INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.90943239]
 [0.88333925]
 [0.90233852]]
LOSS:
0.0034190050522442147


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.90943737]
 [0.88333658]
 [0.90232548]]
LOSS:
0.003418153717588882


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.90944235]
 [0.88333391]
 [0.90231243]]
LOSS:
0.003417302049006288


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.90944733]
 [0.88333124]
 [0.90229937]]
LOSS:
0.003416450045032353


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.90945231]
 [0.88332858]
 [0.9022863 ]]
LOS

INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.91486951]
 [0.88259407]
 [0.88714039]]
LOSS:
0.0025206177111101557


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.91487948]
 [0.88259648]
 [0.88711222]]
LOSS:
0.002519100022685705


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.91488946]
 [0.8825989 ]
 [0.88708402]]
LOSS:
0.0025175812287652915


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.91489945]
 [0.88260134]
 [0.88705579]]
LOSS:
0.002516061329962315


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.91490946]
 [0.8826038 ]
 [0.88702753]]
LO

PREDICTED OP:
[[0.91666543]
 [0.88319763]
 [0.88215831]]
LOSS:
0.0022593431082374646


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.91667759]
 [0.88320277]
 [0.88212533]]
LOSS:
0.002257660199335046


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.91668976]
 [0.88320794]
 [0.88209233]]
LOSS:
0.0022559764169806534


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.91670194]
 [0.88321312]
 [0.88205929]]
LOSS:
0.002254291763509182


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.91671414]
 [0.88321832]
 [0.88202622]]
LOSS:
0.0022526062412676117


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL O

INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.9185882 ]
 [0.88415726]
 [0.87708708]]
LOSS:
0.002007580129998531


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.91860262]
 [0.88416546]
 [0.87705021]]
LOSS:
0.0020058010280046396


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.91861705]
 [0.88417368]
 [0.87701332]]
LOSS:
0.002004021518552973


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.9186315 ]
 [0.88418192]
 [0.8769764 ]]
LOSS:
0.002002241605731031


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.91864597]
 [0.88419019]
 [0.87693946]]
LOS

PREDICTED OP:
[[0.9206318 ]
 [0.88544117]
 [0.8720387 ]]
LOSS:
0.0017708725676852338


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.92064836]
 [0.88545247]
 [0.87199927]]
LOSS:
0.001769078806964426


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.92066493]
 [0.88546379]
 [0.87195983]]
LOSS:
0.0017672852614708252


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.92068151]
 [0.88547514]
 [0.87192038]]
LOSS:
0.0017654919364190641


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.92069811]
 [0.88548651]
 [0.87188091]]
LOSS:
0.0017636988370285731


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL 

LOSS:
0.0014665785061686483


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.92375274]
 [0.88776803]
 [0.86501385]]
LOSS:
0.0014649019587166282


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.92377174]
 [0.88778323]
 [0.86497354]]
LOSS:
0.0014632265378715717


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.92379075]
 [0.88779844]
 [0.86493323]]
LOSS:
0.0014615522484660443


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.92380978]
 [0.88781367]
 [0.86489292]]
LOSS:
0.0014598790953229783


INPUT:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
ACTUAL OP:
[[0.98]
 [0.89]
 [0.83]]
PREDICTED OP:
[[0.92382881]